jobs:
#Deploy DB :
- name: deployDoug
  job:
    deploy:
      contract: Doug/Doug.sol
      instance: all

- name: deployActionDb
  job: 
    deploy:
      contract: Actions/ActionDb.sol
      instance: all

- name: deployActionManager
  job:
    deploy:
      contract: Actions/ActionManager.sol
      instance: all

- name: deployBank
  job:
    deploy: 
      contract: Bank.sol
      instance: all

- name: deployPermissions
  job:
    deploy: 
      contract: Permissions.sol
      instance: all
    

- name: deployUsers
  job:
    deploy:
      contract: Users/UserDb.sol
      instance: all


- name: deployOffers
  job:
    deploy: 
      contract: Offer/OfferDb.sol
      instance: all

- name: deployRewards
  job:
    deploy:
      contract: Reward/RewardDb.sol
      instance: all
      
- name: deployActiveAction 
  job:
    deploy:
      contract: Actions/ActiveAction.sol
      instance: all
      wait: true

#Wait for all to be deployed       
#Then Store DB in DOUG
- name: storeActionDb
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "actiondb"
        - $deployActionDb
      
- name: storeActionManager
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "actions"
        - $deployActionManager

- name: storeBank
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "bank"
        - $deployBank

- name: storePermissions
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "perms"
        - $deployPermissions

- name: storeUsers
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "users"
        - $deployUsers            

- name: storeOffers
  job:
    call: 
      destination: $deployDoug
      abi: Doug
      function: addContract
      data: 
        - "offers"
        - $deployOffers

- name: storeRewards
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data :
        - "rewards"
        - $deployRewards

- name: storeActiveAction
  job: 
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "activeaction"
        - $deployActiveAction
      wait: true

#Deploy Actions
- name: deployActionAddReward
  job:
    deploy:
      contract: Actions/ActionAddReward.sol
      instance: all
      wait: true

- name: deployActionRemoveReward
  job:
    deploy:
      contract: Actions/ActionRemoveReward.sol
      instance: all
      wait: true

- name: deployActionBuyReward
  job:
    deploy:
      contract: Actions/ActionBuyReward.sol
      instance: all
      wait: true

- name: deployActionSpendReward
  job:
    deploy:
      contract: Actions/ActionSpendReward.sol
      instance: all
      wait: true