jobs:

- name: deployDoug
  job:
    deploy:
      contract: Doug/Doug.sol
      instance: all
      wait: true

- name: deployActionDb
  job: 
    deploy:
      contract: Actions/ActionDb.sol
      instance: all
      wait: true   

- name: storeActionDb
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "actiondb"
        - $deployActionDb 

- name: deployActionManager
  job:
    deploy:
      contract: Actions/ActionManager.sol
      instance: all
      wait: true
      
- name: storeActionManager
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "actions"
        - $deployActionManager

- name: deployBank
  job:
    deploy: 
      contract: Bank.sol
      instance: all
      wait: true

- name: storeBank
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "bank"
        - $deployBank

- name: deployPermissions
  job:
    deploy: 
      contract: Permissions.sol
      instance: all
      wait: true   

- name: storePermissions
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "perms"
        - $deployPermissions

- name: deployUsers
  job:
    deploy:
      contract: Users/UserDb.sol
      instance: all
      wait: true

- name: storeUsers
  job:
    call:
      destination: $deployDoug
      abi: Doug
      function: addContract
      data:
        - "users"
        - $deployUsers

- name: deployOffers
  job:
    deploy: 
      contract: Offer/OfferDb.sol
      instance: all
      wait: true      

- name: storeOffers
  job:
    call: 
      destination: $deployDoug
      abi: Doug
      function: addContract
      data: 
        - "offers"
        - $deployOffers
      wait: true

#Deploy db schemas for ABI:
- name: offerAbi
  job:
    deploy: 
      contract: Offer.sol
      wait: true

      #Deploy Actions
- name: deployActionRemoveAction
  job:
    deploy:
      contract: Actions/ActionRemoveAction.sol
      instance: all
      wait: true

- name: deployActionAddUser
  job: 
    deploy: 
      contract: Actions/ActionAddUser.sol
      instance: all
      wait: true


- name: deployActionRemoveUser
  job:
    deploy:
      contract: Actions/ActionRemoveUser.sol
      instance: all
      wait: true

- name: deployActionAddOffer
  job:
    deploy:
      contract: Actions/ActionAddOffer.sol
      instance: all
      wait: true

- name: deployActionRemoveOffer
  job:
    deploy:
      contract: Actions/ActionRemoveOffer.sol
      instance: all
      wait: true

- name: deployActionCommitToOffer
  job: 
    deploy:
      contract: Actions/ActionCommitToOffer.sol
      instance: all
      wait: true

- name: deployActionClaimOffer
  job:
    deploy: 
      contract: Actions/ActionClaimOffer.sol
      instance: all
      wait: true

- name: deployActionConfirmOffer
  job:
    deploy:
      contract: Actions/ActionConfirmOffer.sol
      instance: all      
      wait: true

